create sequence if not exists hibernate_sequence start with 1;

create table employees (
    id bigint generated by default as identity,
    name_ varchar not null unique,

    primary key (id)
);

create table reviews (
    id bigint generated by default as identity,
    employee_id bigint not null,
    title varchar not null,

    primary key (id),
    foreign key (employee_id) references employees(id)
);

create table feedback_assignments (
    id bigint generated by default as identity,
    review_id bigint not null,
    employee_id bigint not null,

    primary key (id),
    foreign key (review_id) references reviews(id),
    foreign key (employee_id) references employees(id)
);

create table feedbacks (
    id bigint generated by default as identity,
    assignment_id bigint not null,
    content varchar not null,

    primary key (id),
    foreign key (assignment_id) references feedback_assignments(id)
);
